#!/bin/bash
printf "Generating README.md... \n"
readme_file=$(pwd)/README.md
rm -f "$readme_file"
tmp=$(pwd)/tmp
dirs=$(ls)
# printf "# Eric Teo\n\n" >"$readme_file"
for dir in $dirs; do

    if [ -f "$dir" ] || [ "$dir" = "SaveOnly" ]; then
        continue
    else
        printf "* %s\n\n" "$dir" >>"$readme_file"
        (
            cd "$dir" || return
            files=$(ls)
            for file in $files; do
                if [ -f "$file" ]; then
                    read -r line <"$file"
                    echo "$line" >"$tmp"
                    # 去掉开头的 #
                    line=$(sed 's/#//g' "$tmp")
                    echo "$line" >"$tmp"
                    # 去掉开头的空格
                    line=$(sed 's/^[ \t]*//g' "$tmp")

                    printf "  * [%s](%s)\n\n" "$line" "$dir/$file" >>"$readme_file"
                fi
            done
        )
    fi
done
printf "\n\n*Do not modify this file, it was generated by ‘generate_readme.sh’ when committing.*\n\n" >>"$readme_file"
rm "$tmp"
printf "Generate README.md successful... \n\n"
git add .
exit 0
