#!/bin/bash
printf "Generating blog.md... \n"

# 先检查文章有没有更新，节省一点时间
article_update=$(git diff --cached --name-only --grep blog/*/*.md)
if [ ! "$article_update" ]; then
    echo 'Skip generating blog.md... '
    exit 0
fi

file_name=$(pwd)/blog.md
rm -f "$file_name"
tmp=$(pwd)/tmp
cd blog || exit 1
dirs=$(ls)

echo '---' >"$file_name"
printf '  layout: blog\n  title: Blog\n  slug: /blog\n' >>"$file_name"
echo '---' >>"$file_name"

for dir in $dirs; do
    if [ -f "$dir" ] || [ "$dir" = "SaveOnly" ]; then
        continue
    else
        printf "* %s\n\n" "$dir" >>"$file_name"
        (
            cd "$dir" || return
            files=$(ls)
            for file in $files; do
                if [ -f "$file" ]; then
                    read -r line <"$file"
                    echo "$line" >"$tmp"
                    # 去掉开头的 #
                    line=$(sed 's/#//g' "$tmp")
                    echo "$line" >"$tmp"
                    # 去掉开头的空格
                    line=$(sed 's/^[ \t]*//g' "$tmp")

                    printf "  * [%s](blog/%s)\n\n" "$line" "$dir/$file" >>"$file_name"
                fi
            done
        )
    fi
done
# printf " \n\n*** \n\n*Do not modify this file, it was generated by ‘generate_blog.sh’ when committing.*\n\n" >>"$file_name"
rm "$tmp"
printf "Generate blog.md successful... \n\n"
git add "$file_name"
exit 0
